name: RandomNick
main: Random\Main
version: 1.0
api: 2.0.0, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
author: UltimateDevs
commands:
  nick:
    description: "Nick yourself with a random nickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give your a random nick"
  default: op
