name: RandomNick
main: Random\Main
version: 1.0
api: 2.0.0
author: UltimateDevs
commands:
  nick:
    description: "Nick yourself with a random nickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give you a random nick"
  default: op
