name: RandomNick
main: Random\Main
version: 1.0
api: 2.0.0
author: UltimateDevs
commands:
  nick:
    description: "Nick yourself with a RandomNickname!"
    aliases: [n,nickname]
    permission: nick
    
permissions:
 nick:
  description: "Allow to give your a Random nick"
  default: op
